"""Initial migration

Revision ID: c6b8071f1be6
Revises: 
Create Date: 2024-04-28 16:58:38.821716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b8071f1be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('transcription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('transcription')
        batch_op.drop_column('audio_file_path')

    # ### end Alembic commands ###
